services:
    react:
        build:
            dockerfile: Dockerfile
            context: frontend
        image: gla-react-frontend
        container_name: gla-react
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/src:/usr/app/src
            - ./frontend/public:/usr/app/public
            - ./frontend/playwright:/usr/app/playwright
        networks:
            - gla-react-network
    # db:
    #     image: mysql
    #     command: --default-authentication-plugin=mysql_native_password
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #     networks:
    #         - gla-react-network
    #     ports:
    #         - "3316:3306"
    
networks:
    gla-react-network:
        driver: bridge

# volumes:
