-- Create a table for log entries
CREATE TABLE IF NOT EXISTS public.log (
  id bigint GENERATED BY DEFAUlT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT "now"() NOT NULL,
  severity public.log_type NOT NULL,
  message text NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE SET NULL
);
ALTER TABLE public.log ENABLE ROW LEVEL SECURITY;

-- Create a table specifying who can access the logs
CREATE TABLE IF NOT EXISTS public.log_viewers (
    user_id uuid PRIMARY KEY REFERENCES auth.users(id)
);
ALTER TABLE public.log_viewers ENABLE ROW LEVEL SECURITY;

-- Create policies to use the second table to control the first table
CREATE POLICY "Select yourself" 
  ON public.log_viewers
  FOR SELECT 
  TO authenticated
  USING (user_id = (SELECT auth.uid()));
CREATE POLICY "Specified users (log_viewers) can access the logs"
  ON public.log
  FOR SELECT
  TO authenticated
  USING (
    (SELECT auth.uid()) 
    IN 
    (
      SELECT log_viewers.user_id
      FROM public.log_viewers
    )
  );
