-- Fix broken ticket issuing caused by a drifted public.log identity sequence.
--
-- Background
-- ----------
-- public.log.id is `GENERATED BY DEFAULT AS IDENTITY`. BY DEFAULT (rather than
-- ALWAYS) lets a caller supply an explicit id, and doing so does NOT advance
-- the backing sequence (log_id_seq). A dump/restore or data import that wrote
-- explicit ids therefore leaves log_id_seq behind MAX(log.id). The next
-- auto-generated id then collides with an existing row -> duplicate primary
-- key on insert.
--
-- 20260528110000 added an AFTER INSERT trigger (log_new_ticket) that writes to
-- public.log inside the same transaction as the ticket INSERT. With a drifted
-- sequence, that log write fails with a duplicate-key error, the exception
-- propagates, and get_or_create_ticket's INSERT rolls back -- so ticket issuing
-- fails outright (and the page's fallback logToDb('error', ...) hits the same
-- duplicate-key error, which is what surfaces in the Vercel logs).
--
-- This migration:
--   1. Resyncs log_id_seq to MAX(log.id) + 1 so generated ids stop colliding.
--   2. Hardens log_new_ticket() so a log-write failure can never roll back the
--      ticket transaction again -- audit logging must not block the business
--      operation it observes.


-- =============================================================================
-- 1. Resync the log identity sequence
-- =============================================================================
-- setval(..., MAX(id) + 1, false): is_called = false means the *next* nextval()
-- returns exactly MAX(id) + 1 (not MAX(id) + 2). COALESCE handles an empty table
-- (next value becomes 1). pg_get_serial_sequence resolves the identity sequence
-- without hardcoding its name.
SELECT setval(
  pg_get_serial_sequence('public.log', 'id'),
  (SELECT COALESCE(MAX(id), 0) FROM public.log) + 1,
  false
);


-- =============================================================================
-- 2. Make the ticket-log trigger non-fatal
-- =============================================================================
-- Wrap the insert in an exception block so any failure (duplicate key, RLS,
-- etc.) is caught and the ticket creation still commits. The trigger remains
-- SECURITY DEFINER with a pinned empty search_path (see 20260528110000 for the
-- rationale on both); only the body gains the exception handler.
CREATE OR REPLACE FUNCTION public.log_new_ticket()
  RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
AS $$
BEGIN
  BEGIN
    INSERT INTO public.log (severity, message, source, user_id, context, expires_at)
    VALUES (
      'info',
      'New ticket created',
      'ticket/issue',
      NEW.user_id,
      jsonb_build_object('ticketNumber', NEW.ticket_number),
      NOW() + INTERVAL '180 days'
    );
  EXCEPTION WHEN OTHERS THEN
    -- Logging is best-effort: never let an audit-log write abort the ticket
    -- transaction. Surface the failure as a warning for server-log triage.
    RAISE WARNING 'log_new_ticket: failed to write log row for ticket % (user %): %',
      NEW.ticket_number, NEW.user_id, SQLERRM;
  END;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.log_new_ticket() FROM PUBLIC;
